### PR TITLE
Little fixes for Day 2

### PR DESCRIPTION
**Pull request by akokai**
Only thought of a few really minor things so far.
- **Lists:** Can't seem to access the `<function>?` help mechanism in Jupyter for methods. Running, e.g., `''.join?` just returned "Object not found" or something like that. So instead, suggesting to look up the docs on `join` and clarifying that it's a string method, not a list method.
- **Loops:** The use of loops + conditionals to "evolve" a variable iteratively needed a bit of contextualization & explanation. People were a bit mystified why anyone would do this. I suggested population modeling (ecology, etc.) as one possible reason.

### CODE REVIEW

**Comment by akokai** [comment]
One more thing:
- **Lists:** Added explanation of the behavior of variables created by slicing a list, when the original list gets changed. This is counterintuitive because of the mutability of lists, etc. Maybe someone should review my explanation to make sure it's not confusing.

**Comment by henchc** [comment]
in jupyter you have to type the datatype to get the help:

```
str.join?
str.split?
list.append?
list.extend?
```

did that work for you? but going to the docs works too, if it works, can you add the str.join? back to the notebook as a second reference?

all the other changes look great, we'll let @alexestes  and @natalieahn give input, then go ahead and merge

**Comment by alexestes** [comment]
Looks good to me!

On Fri, Sep 23, 2016 at 3:26 PM, Christopher Hench <notifications@github.com

**Comment by natalieahn** [comment]
Changes look good to me too!

**Comment by akokai** [comment]
Hah, TIL that you need to say `str.join?` :) Thanks, it works. I reinstated the Jupyter help thing as the primary course of action, with a link to the Python docs just to show people that all of this is also on a website you can access outside of Jupyter. 

I'm still not fully satisfied with the 'population' loops/conditionals example – I have a feeling we can find a more intuitive and straightforward example of that pattern – but I'll leave it for now.

I think we can merge this whenever the intensive series is done.

**Pull request merged**
